apiVersion: apps/v1
kind: Deployment
metadata:
  name: next-web-server
  namespace : ardin
  labels:
    app: web-server
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80