apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: ardin
  labels:
    app.kubernetes.io/name: proxy
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
      - containerPort: 80
       

